kind: Deployment
apiVersion: apps/v1
metadata:
  name: eregister-frontend
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eregister-frontend
  template:
    metadata:
      labels:
        app: eregister-frontend
    spec:
      containers:
      - name: eregister-frontend
        imagePullPolicy: Always
        image: us-west2-docker.pkg.dev/prime-chess-368907/docker-repo/eregister-frontend
        ports:
        - containerPort: 3000
