kind: Deployment
apiVersion: apps/v1
metadata:
  name: eregister-user-service
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eregister-user-service
  template:
    metadata:
      labels:
        app: eregister-user-service
    spec:
      containers:
      - name: eregister-user-service
        imagePullPolicy: Always
        image: us-west2-docker.pkg.dev/prime-chess-368907/docker-repo/eregister-user-service
        ports:
        - containerPort: 10000
