kind: Service
apiVersion: v1
metadata:
  name: eregister-frontend
  namespace: ingress-nginx
spec:
  selector:
    app: eregister-frontend
  ports:
  - name: http-port
    protocol: TCP
    targetPort: 3000
    port: 3000
